### PR TITLE
Add basic integration tests

### PR DESCRIPTION
**Pull request by bogdan0083**
Hello! I've been using this plugin for quite a long time now and decided to add some simple integration tests so that we can add new functionality to the plugin without breaking the foundation. I would be happy to hear your thoughts on what should I add/improve/change in this PR.

We've got the problem though. It seems that right now the tests are only passing on Windows because we receive different path separators across Unix and Windows. For example:

Windows
```js
Search Query: foo
Containing Folder: f:\projects\better-search
Total Results: 85
Total Files: 10

File: src\test\search\search.test.ts
32   		const location = getSamplesLocation('search');
33   		const expected = read('search/results/expected-multiple-extensions.txt');
34   		const result = await runBetterSearch({ query: 'foo', location });
35   		expect(result).to.equal(expected);
36   	});
```

UNIX
```js
Search Query: foo
Containing Folder: /home/projects/better-search
Total Results: 85
Total Files: 10

File: src/test/search/search.test.ts
32   		const location = getSamplesLocation('search');
33   		const expected = read('search/results/expected-multiple-extensions.txt');
34   		const result = await runBetterSearch({ query: 'foo', location });
35   		expect(result).to.equal(expected);
36   	});
```

And that makes our tests inconsistent across the different OS. I wanna hear your thoughts on this issue. Should we replace backslash with a slash or wrap it in `Uri.file` and get `path` property? I don't know. All these approaches are quite hacky but maybe you can come up with something better. 😄 

Thank you! :heart:

### CODE REVIEW

**Comment by thieman** [comment]
Excited to take a look at this, thanks for all your effort so far!

**Comment by bogdan0083** [comment]
I've just realized that the tests are passing only on my PC since the 'Containing Folder:' line has the full path to search folder.

Will try to come up with a fix tomorrow 😄

**Comment by bogdan0083** [comment]
Tests now should pass just fine on Unix-based systems (tested on ubuntu 18.04) 🎉

**Comment by bogdan0083** [comment]
/cc @thieman 

Alright, I guess this PR is ready for a review now. :smile: I would be happy if you could clone the branch in your spare time and try to run the tests to make sure they are passing for you. I tested it on Windows and Ubuntu - works like a charm!

**Comment by thieman** [comment]
I'm having some trouble actually getting the tests to run, how were you doing it?

**Comment by bogdan0083** [comment]
1. Clone the repo and switch to `add-tests` branch
2. Open the cloned repo with vscode
3. Run `npm i` from the terminal to install all dependencies
4. From vscode go to Debug > Start debugging (or just press F5)
5. Click on the button with PLAY icon on the bottom and choose `Extension Tests`:

6. If everything is fine the new window will open. You can open the `Debug Console` and see the tests pass/fail.

**Comment by bogdan0083** [comment]
Alright, I just ran `npm run test` with vscode closed and the tests fail. I guess they are passing only if we run tests from vscode, which is not correct. I'll see what I can do to fix this tomorrow. The tests should pass from cli as well as from vscode.

**Comment by thieman** [comment]
One fix I did need to make was remove `yarn` from the `test` script in npm. Now it's complaining about mocha stuff not being found (`suite is not defined`) when I run from CLI. :thinking:

**Comment by bogdan0083** [comment]
hmm.. Try to remove the `out` folder and run `yarn compile`. Now try to run the tests again. Does it work?

**Comment by thieman** [comment]
I'll throw up a branch, just a sec

**Comment by thieman** [comment]
Works continues over in #29.

**Pull request closed without merging**
