### PR TITLE
Start of test suite

### PR DESCRIPTION
**Pull request by thieman**
Continuation of #26

### CODE REVIEW

**Comment by thieman** [comment]
@bogdan0083 With that commit I can run `npm run test` and it'll run the suite. Some tests are currently failing, though. Were you having any of the problems with the Mocha interface? I couldn't figure out how to get it to play nicely with the BDD interface at all

**Comment by bogdan0083** [comment]
@thieman Thanks! I'll clone this branch tomorrow and try to make sure tests are passing from cli. I wonder why it shows `suite is not defined` error though? Can you please switch to my branch, remove `out` folder and run `yarn run compile` (or `npm run compile`)? Does it show the error with the `suite` stuff now? I had the same error for a while and I'm curious why it's present.

**Comment by thieman** [comment]
I'm pushing forward and I think I'll be able to get it to work, should have something soon

**Comment by thieman** [comment]
Alright, `npm test` is working from CLI right now. Changes:

1. Moved the sample files into a `doc/` folder at top dir so TypeScript stopped trying to compile them. Also excluded `doc/` from TS build process.
2. Defaulted tests to context 2 (extension default) and made it always sortFiles so the output is deterministic. Without this, the output wasn't coming out in the same order as the fixtures.

**Comment by thieman** [comment]
3. Changed the workspace dir in the launch.json to the project root. Tests now complete successfully when run from inside VSCode.

I'd like to get all this stuff running in CI using GitHub Actions, take a final pass on style stuff, then merge it!

**Comment by bogdan0083** [comment]
Great! 🎉 I was about to ask for Travis CI integration but Github Actions is also fine 👍

**Comment by thieman** [comment]
Alright actions is being annoying (just saying `This check failed` with no other information whatsoever) so I'll do that in a follow-up PR instead

**Comment by thieman** [comment]
Gonna go ahead and merge this one since I've got the suite working, will follow up with more stuff on the actions front. Thanks again!

**Comment by bogdan0083** [comment]
Hooray! I'll create a PR tomorrow with the new case-sensitibility parameters (ignorecase and smartcase) tomorrow to check how CI integration is doing.

**Pull request merged**
